name: Deploy to GCP

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push Docker image
        run: |
          echo ${{ steps.docker-auth.outputs }}
          docker build \
            -t europe-west3-docker.pkg.dev/givery-recipe-app/givery-recipe-api/app:${{ github.sha }} \
            ./
          docker push "europe-west3-docker.pkg.dev/givery-recipe-app/givery-recipe-api/app:${{ github.sha }}"
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: givery-recipe-api
          region: ${{ secrets.GCP_REGION }}
          image: europe-west3-docker.pkg.dev/givery-recipe-app/givery-recipe-api/app:${{ github.sha }}
